### ISSUE TITLE
Crash when open filter screen.

### ISSUE THREAD

**Issue by tienthanh2929** [Lileep/PixelmonDetector#10]
Great mod, thanks for porting this to 1.16.5!

But I have a problem, when I opened the filter screen, the game straight up crashed.

https://bytebin.lucko.me/LSqi2WDTlb

Updated:
Tested with only Pixelmon 9.1.3, JourneyMap and Not Enough Crash, the same crash still occur.

**Comment by Lileep** [comment]
Thx for ur reply!
I'll have a check about the usage of the translation key `pixelmondetector.gui.search.title`. And if it is convenient for u and u're interested in it, u may write a lang file that is in ur language and send it to me, then I'll mark it as ur contribute too and put it into the mod. Ty!

**Comment by Lileep** [comment]
> > Thx for ur reply! I'll have a check about the usage of the translation key `pixelmondetector.gui.search.title`. And if it is convenient for u and u're interested in it, u may write a lang file that is in ur language and send it to me, then I'll mark it as ur contribute too and put it into the mod. Ty!
> 
> Writing a lang file does not solve the problem, really odd. The lang file did work correctly, but the crash still occurs when I open the filter screen.
> 
> Is it possible for me to obtain the source code? Thanks!!

Oh, that's kinda weird. Maybe there're conflicts between the detector and some other mods. I'll go over ur crash log again later.

As for the source code, it is not published yet due to [issue 3](https://github.com/Lileep/PixelmonDetector/issues/3). I've uploaded one in the dropbox. If u really want it, reply again and I'll send u the download link.

**Comment by Lileep** [comment]
> > Thx for ur reply! I'll have a check about the usage of the translation key `pixelmondetector.gui.search.title`. And if it is convenient for u and u're interested in it, u may write a lang file that is in ur language and send it to me, then I'll mark it as ur contribute too and put it into the mod. Ty!
> 
> Writing a lang file does not solve the problem, really odd. The lang file did work correctly, but the crash still occurs when I open the filter screen.
> 
> Is it possible for me to obtain the source code? Thanks!!

Wait a min, I think I figure out the problem. It is because the author credits part in the left bottom corner of the filter gui doesn't use the lang file but use a static fields inside the code to avoid being edited. XD

![image](https://github.com/Lileep/PixelmonDetector/assets/103249400/e5781258-1efd-4fdc-89ec-4c9fee551798)

![image](https://github.com/Lileep/PixelmonDetector/assets/103249400/534b6d81-c8ff-4de9-90b4-fb22d3dba899)

My bad, I'll solve it in the next version. Thx again and sry for my late reply, kinda busy these days.

**Comment by Lileep** [comment]
> > > > Thx for ur reply! I'll have a check about the usage of the translation key `pixelmondetector.gui.search.title`. And if it is convenient for u and u're interested in it, u may write a lang file that is in ur language and send it to me, then I'll mark it as ur contribute too and put it into the mod. Ty!
> > > 
> > > 
> > > Writing a lang file does not solve the problem, really odd. The lang file did work correctly, but the crash still occurs when I open the filter screen.
> > > Is it possible for me to obtain the source code? Thanks!!
> > 
> > 
> > Oh, that's kinda weird. Maybe there're conflicts between the detector and some other mods. I'll go over ur crash log again later.
> > As for the source code, it is not published yet due to [issue 3](https://github.com/Lileep/PixelmonDetector/issues/3). I've uploaded one in the dropbox. If u really want it, reply again and I'll send u the download link.
> 
> @Lileep I would love to receive the source code; I also send you a DM on Discord too! So you can send it there and don't have to worry about deleting it later.
> 
> The translated text of: `Pixelmon Detector is developed by a cute Lileep. This mod is completely free. If you purchased it from someone else, please refund and report it to Lileep immediately`
> 
> In my language, it should be: `Pixelmon Detector được tạo bởi Lileep. Mod này hoàn toàn miễn phí. Nếu bạn mua từ ai đó, nghĩa là bạn đã bị lừa hãy báo cáo cho Lileep về vấn đề này.`
> 
> Here's the translated json file. The language is Vietnamese, which is `vi_vn.json`
> 
> ```json
> {
>   "key.categories.pixelmondetector": "Pixelmon Detector",
> 
>   "key.pixelmondetector.trigger": "Bật/Tắt Pixelmon Detector",
>   "key.pixelmondetector.detector": "Mở Lọc Pokémon",
> 
>   "pixelmondetector.finder.msg.meter": "m",
> 
>   "pixelmondetector.finder.msg.legendary": "Legendary",
>   "pixelmondetector.finder.msg.ultra_beast": "Ultra Beast",
> 
>   "pixelmondetector.finder.msg.player": "Player",
>   "pixelmondetector.finder.msg.npc_trainer": "NPC Trainer",
>   "pixelmondetector.finder.msg.npc": "NPC",
> 
>   "pixelmondetector.finder.msg.loot.hidden": "Hidden",
>   "pixelmondetector.finder.msg.loot.special": "Special",
>   "pixelmondetector.finder.msg.loot": "PokeLoot",
> 
>   "pixelmondetector.finder.msg.pokestop.can": "Nhặt được",
>   "pixelmondetector.finder.msg.pokestop.cannot": "Không nhặt được",
> 
>   "pixelmondetector.finder.msg.shrine": "Đền",
>   "pixelmondetector.finder.msg.gadget": "Gadget",
> 
> 
>   "pixelmondetector.gui.search.title": "Tìm Pokémon",
>   "pixelmondetector.gui.search.left_button": "<",
>   "pixelmondetector.gui.search.right_button": ">",
> 
>   "pixelmondetector.gui.search.condition_mode.and": "VÀ",
>   "pixelmondetector.gui.search.condition_mode.or": "HOẶC",
> 
>   "type.mystery": "???"
> }
> ```
> 
> Thank you!

Great! Thx for ur contribution, I'll add u in discord, see u there!

**Comment by Lileep** [comment]
Fixed in 1.2
