### ISSUE TITLE
No way to filter through un-dexed mons

### ISSUE THREAD

**Issue by Lars146** [Lileep/PixelmonDetector#14]
If there would be a function like undexed to show all the Pokemon around you that you currently do NOT have in your PokéDex that would be a great feature in my opinion. I don't know if thats possible to implement doe

**Comment by Lileep** [comment]
Thx for ur reply!
This issue has been reported by @DarkVillager and I might not consider to fix it. See [Issue 8](https://github.com/Lileep/PixelmonDetector/issues/8)
