### ISSUE TITLE
crash open filter

### ISSUE THREAD

**Issue by Bazookamom** [Lileep/PixelmonDetector#19]
the game crashes when I open the filter to search for Pokémon

**Comment by Lileep** [comment]
Thx for ur reply!
Could u send the crash report and briefly describe how to reproduce this issue?

**Comment by Bazookamom** [comment]
[crash-2023-10-03_14.10.05-client.txt](https://github.com/Lileep/PixelmonDetector/files/12795599/crash-2023-10-03_14.10.05-client.txt)

**Comment by Bazookamom** [comment]
at the beginning the filter works but then every time I open it it makes me close the game and it crashes

**Comment by Lileep** [comment]
> at the beginning the filter works but then every time I open it it makes me close the game and it crashes

Hi there, I think I figured out the problem. It is cuz the language u use isn't in either language files or credits info inside the mod. There's a mistake in code that leads to this issue, causing English fallback method doesn't work well. Currently, changing ur language to one that already exists like en_us will solve the problem. Also, I'd appreciate it if u could write a language file and credits info in ur language and send it to me. I'll add it to mod in the next version! :D

**Comment by Lileep** [comment]
Solved in 1.3.1. Don't forget to consider to write a language file and credits info in ur language~
