### ISSUE TITLE
My game stuck when install the mod pls help :(

### ISSUE THREAD

**Issue by kalijones** [Lileep/PixelmonDetector#20]
![image](https://github.com/Lileep/PixelmonDetector/assets/25445289/32f162aa-eb25-4459-a1f2-093177b9c44a)

**Comment by kalijones** [comment]
This all mods i use but i think the reason is server cuz i use it normally in some server except complex gaming server
![image](https://github.com/Lileep/PixelmonDetector/assets/25445289/c550d42d-376b-4576-a547-775bd84ae97f)
all of thing you mentione is last update already

**Comment by Lileep** [comment]
> This all mods i use but i think the reason is server cuz i use it normally in some server except complex gaming server ![image](https://user-images.githubusercontent.com/25445289/281281680-c550d42d-376b-4576-a547-775bd84ae97f.png) all of thing you mentione is last update already

Then that might 'cuz the server u join applies some restrict measures to Pixelmon Detector. U may not be able to use this in that server :(

**Comment by kalijones** [comment]
dat quite sad, btw tks dor support me

**Comment by Lileep** [comment]
> dat quite sad, btw tks dor support me

Np, bro B-)
