### ISSUE TITLE
 too new version

### ISSUE THREAD

**Issue by matuszevsky** [Lileep/PixelmonDetector#21]
hey, are you able to downgrade the mod to version 1.12.2? for pixelmon dark 8.7.1?

**Comment by Lileep** [comment]
> hey, are you able to downgrade the mod to version 1.12.2? for pixelmon dark 8.7.1?

Thx for ur reply!
Since some pixelmon features that Detector used are only existed in 1.16, so the Detector probably won't have a 1.12 version.
But there's a lot of PixelRadar in 1.12.2 version that performs similar to this Pixelmon Detector. U can have a search and install that one :)
