### ISSUE TITLE
Lines glitch

### ISSUE THREAD

**Issue by DarkVillager** [Lileep/PixelmonDetector#22]
Video => [https://streamable.com/gx2uvv](https://streamable.com/gx2uvv)

**Comment by Lileep** [comment]
Thx for ur reply!
That's kinda interesting, haven't seen this circumstance before. Could u show details about the process of reproducing this issue?
I guess maybe it's caused by mod conflicts. There's a simple way that can check if this issue is caused by conflicts: U can temporarily remove all other mods except Pixelmon and Pixelmon Detector, then try again in ur game. If this issue doesn't happen, it may caused by mod conflicts, and u may need to check your mods one by one to figure out which mod caused this issue, then tell me; if this issue still happens, then it may be an issue inside Pixelmon Detector, and u may post ur `latest.log` file here in ur `.minecraft/logs` folder, I'll check and try to fix it. Good luck! B-)

**Comment by DarkVillager** [comment]
> Thx for ur reply! That's kinda interesting, haven't seen this circumstance before. Could u show details about the process of reproducing this issue? I guess maybe it's caused by mod conflicts. There's a simple way that can check if this issue is caused by conflicts: U can temporarily remove all other mods except Pixelmon and Pixelmon Detector, then try again in ur game. If this issue doesn't happen, it may caused by mod conflicts, and u may need to check your mods one by one to figure out which mod caused this issue, then tell me; if this issue still happens, then it may be an issue inside Pixelmon Detector, and u may post ur `latest.log` file here in ur `.minecraft/logs` folder, I'll check and try to fix it. Good luck! B-)

[https://paste.atlauncher.com/view/42eb5f41-43eb-41ed-a8cd-1163771a4f6c](https://paste.atlauncher.com/view/42eb5f41-43eb-41ed-a8cd-1163771a4f6c)

**Comment by Lileep** [comment]
> > Thx for ur reply! That's kinda interesting, haven't seen this circumstance before. Could u show details about the process of reproducing this issue? I guess maybe it's caused by mod conflicts. There's a simple way that can check if this issue is caused by conflicts: U can temporarily remove all other mods except Pixelmon and Pixelmon Detector, then try again in ur game. If this issue doesn't happen, it may caused by mod conflicts, and u may need to check your mods one by one to figure out which mod caused this issue, then tell me; if this issue still happens, then it may be an issue inside Pixelmon Detector, and u may post ur `latest.log` file here in ur `.minecraft/logs` folder, I'll check and try to fix it. Good luck! B-)
> 
> https://paste.atlauncher.com/view/42eb5f41-43eb-41ed-a8cd-1163771a4f6c
> 
> [latest.log](https://github.com/Lileep/PixelmonDetector/files/13801466/latest.log)

Umm, unfortunately, it seems that this log doesn't show any issues with Pixelmon Detector. Have you confirmed that this is not a mod conflict? i.e. only keep Pixelmon and Pixelmon Detector in ur game and launch to see whether this issue happens.

**Comment by Lileep** [comment]
Additionally, r u playing a server or a client? Since plugins in servers may also conflict with the Pixelmon Detector.

**Comment by DarkVillager** [comment]
> Additionally, r u playing a server or a client? Since plugins in servers may also conflict with the Pixelmon Detector.

Singleplayer world.

**Comment by Lileep** [comment]
> > Additionally, r u playing a server or a client? Since plugins in servers may also conflict with the Pixelmon Detector.
> 
> Singleplayer world.

I tried in both 9.1.9 and 9.1.10, Detector works well. I can't figure out what's wrong with your client. U can try to downgrade ur Detector version to 1.4 or 1.3.1 to see whether if this issue happens and tell me the result. Besides, u may try to upgrade ur forge version to `36.2.39`, since I use this version for development.

**Comment by Lileep** [comment]
And I notice that u're using resource packs. U may remove it and try again. The first important thing we need to confirm is the cause of the problem, since no player I know who uses 1.5 Detector has this problem. So please try more and reply more. If it's necessary, u could send out ur client file and I'll try in ur client.

**Comment by DarkVillager** [comment]
> And I notice that u're using resource packs. Just remove it and try again. The first important thing we need to confirm is the cause of the problem, since no other players I know who use 1.5 Detector has this problem. So please try more and reply more. If it's necessary, u could send out ur client file and I'll try in ur client.

Sorry i have been having busy I will try my best to do this tomorrow.

**Comment by Lileep** [comment]
> > And I notice that u're using resource packs. Just remove it and try again. The first important thing we need to confirm is the cause of the problem, since no other players I know who use 1.5 Detector has this problem. So please try more and reply more. If it's necessary, u could send out ur client file and I'll try in ur client.
> 
> Sorry i have been having busy I will try my best to do this tomorrow.

Np~Feel free to reply after u try.

**Comment by DarkVillager** [comment]
Updating forge didnt solve it.

**Comment by Lileep** [comment]
> 1- Updating forge DIDNT solve it. 2- Removing all resourcepacks DIDNT solve it. 3- Downgrading to 1.4/1.3.1 DIDNT solve it.

Quite weird. If all above operations aren't work, then this may be a problem with your client itself. U may send me ur client and I'll have a try.
Btw, didn't you find similar issues before when you used versions 1.3.1 and 1.4?

**Comment by Lileep** [comment]
Since my here works fine.
<img width="423" alt="image" src="https://github.com/Lileep/PixelmonDetector/assets/103249400/36ab43e8-b99f-4c37-a720-98b9ba6c211b">

**Comment by DarkVillager** [comment]
> > 1- Updating forge DIDNT solve it. 2- Removing all resourcepacks DIDNT solve it. 3- Downgrading to 1.4/1.3.1 DIDNT solve it.
> 
> Quite weird. If all above operations don't work, then this may be a problem with ur client itself. U may send me ur client and I'll have a try. Btw, didn't you find similar issues before when you used versions 1.3.1 and 1.4?
I didnt have issues before.

**Comment by Lileep** [comment]
> > > 1- Updating forge DIDNT solve it. 2- Removing all resourcepacks DIDNT solve it. 3- Downgrading to 1.4/1.3.1 DIDNT solve it.
> > 
> > 
> > Quite weird. If all above operations don't work, then this may be a problem with ur client itself. U may send me ur client and I'll have a try. Btw, didn't you find similar issues before when you used versions 1.3.1 and 1.4?
> 
> I didnt have issues before.

Umm, u may tell me more, like when did you start having this issue? Is it after replacing the Detector with a new version or after using it on a new client? If it is the first case, which two versions did u find this issue when switching between them? If it is the second case, which client did u use to cause this issue? U can send me a copy of the client and I'll try it, or show me ur java version, forge version and mod list (I've seen it in the log before, so mod list may not be needed), and I'll try it further. I have tried it in the environment of java8 & java 11, forge36.2.34 to 36.2.39, Pixelmon 9.1.9 to 9.1.10, and Pixelmon Detector 1.3.1 to 1.5 without this issue. 
Pls tell me in detail, it'll help me to judge the situation. Simply saying you don't have this problem in xxx situation won't help for fixing. And send me a client u're using if it is convie1- Updating forge DIDNT solve it. 2- Removing all resourcepacks DIDNT solve it. 3- Downgrading to 1.4/1.3.1 DIDNT solve it.
> > 
> > 
> > Quite weird. If all above operations don't work, then this may be a problem with ur client itself. U may send me ur client and I'll have a try. Btw, didn't you find similar issues before when you used versions 1.3.1 and 1.4?
> 
> I didnt have issues before.

Umm, u may tell me more, like when did you start having this issue? Is it after replacing the Detector with a new version or after using it on a new client? If it is the first case, which two versions did u find this issue when switching between them? If it is the second case, which client did u use to cause this issue? U can send me a copy of the client and I'll try it, or show me ur java version, forge version and mod list (I've seen it in the log before, so mod list may not be needed), and I'll try it further. I have tried it in the environment of java8 & java 11, forge36.2.34 to 36.2.39, Pixelmon 9.1.9 to 9.1.10, and Pixelmon Detector 1.3.1 to 1.5 without this issue. 
Pls tell me in detail, it'll help me to judge the situation. Simply saying you don't have this problem in xxx situation won't help for fixing. Also send me the client u're using if convenient.

**Comment by Lileep** [comment]
I just let my 3 mates tried this with a mod list in ur log, they all get good lines.

**Comment by DarkVillager** [comment]
> I just let my 3 mates tried this with a mod list in ur log, they all get good lines.

I replaced my java… iirc

**Comment by Lileep** [comment]
> > I just let my 3 mates tried this with a mod list in ur log, they all get good lines.
> 
> I replaced my java… iirc

So if u change ur java back, will Detector work well?

**Comment by DarkVillager** [comment]
> > > I just let my 3 mates tried this with a mod list in ur log, they all get good lines.
> > 
> > 
> > I replaced my java… iirc
> 
> So if u change ur java back, will Detector work well? Also what version of java r u currently using?

Let me check with the launcher's developer, since only  java-runtime-beta (Java 17.0.1.12.1) works, due to some errors i have with my dockingstation.

**Comment by Lileep** [comment]
> > > > I just let my 3 mates tried this with a mod list in ur log, they all get good lines.
> > > 
> > > 
> > > I replaced my java… iirc
> > 
> > 
> > So if u change ur java back, will Detector work well? Also what version of java r u currently using?
> 
> Let me check with the launcher's developer, since only java-runtime-beta (Java 17.0.1.12.1) works, due to some errors i have with my dockingstation.

Kk. It's recommend to use java 8 or 11 when playing 1.16.5, other versions may not guarantee the stability of mods in 1.16.5. So have a try :)

**Comment by Lileep** [comment]
So it's been a month now, how's this issue going?

**Comment by DarkVillager** [comment]
> So it's been a month now, how's this issue going?

Still the same but doesn't seem like an issue from the mod, just java being java.

**Comment by Lileep** [comment]
Kk, have a nice day~ XD
