### ISSUE TITLE
Resource pack interrupting 

### ISSUE THREAD

**Issue by Pokehunter007** [Lileep/PixelmonDetector#26]
I asked the owner and he said he didn't know anything about pixelmon detector but I noticed that when I join server ,before the server resources pack load fully , i can still see pokeloots ,pokestops , legendary etc but after its loaded only search function works .
Any solution to this ?
Thank you.

**Comment by Lileep** [comment]
Ty for ur reply!
I'm not quite sure what situations u said, could u describe it in detail? U mean that when u enter servers and the resourcepack is not loaded, the tracking is effective, but when the resourcepack is loaded, the tracking won't work?

**Comment by Pokehunter007** [comment]
Yes.

**Comment by Lileep** [comment]
> Yes.

That's kinda weird. One possibility is that the server u're playing on has some kind of anti-cheat plugins/mods that restricts the function of the Detector via manipulating the resourcepacks. If that's the case, there's nothing we can do. In addition, if the server has installed Pixelmon Detector, the config file of ur client would be based on the server. The server owner is able to limit ur client Detector behavior in this way.

Now let's go into a little more detail, which may help identify the problem. Which version of Pixelmon Detector r u using? And what resourcepack is used? Which server r u playing?

**Comment by Lileep** [comment]
So it's been 2 weeks ago, how's this issue going?

**Comment by Lileep** [comment]
It has been a month since this issue was created and there're no more replies, so I'll close this. If u still have questions, feel free to open a new one!
