### ISSUE TITLE
Mod for Pixelmon 1.12.2

### ISSUE THREAD

**Issue by TinasDG** [Lileep/PixelmonDetector#28]
Hey, can u make an 1.12.2 version for this mod?

**Comment by Lileep** [comment]
Hi, ty for ur replying!
For 1.12 version, u may use [PixelRadar](https://gitee.com/ancientsky_studio/pixelradar). It contains not only tracking functions, but also minimaps.

**Comment by TinasDG** [comment]
Pixelradar didnt work in the server i use to play :(

**Comment by Lileep** [comment]
> Pixelradar didnt work in the server i use to play :(

Then there's nothing we can do about it. PixelRadar has stronger anti anti-cheat features inside. As a result, if the server u play on can block PixelRadar, it can block PixelmonDetector more easily.
