### ISSUE TITLE
Support Pixelmon 9.2.5, mc 1.20.2

### ISSUE THREAD

**Issue by elguillerexg** [Lileep/PixelmonDetector#30]
can be made compatible with pixelmon 1.20.2 9.2.5?

**Comment by Lileep** [comment]
Hi there, ty for ur reply!
For lower 1.20.2 versions like 9.2.4 & 9.2.5 supporting, you can manually modify the version range in `META-INF/mods.toml` file inside Pixelmon Detector mod (Open it with some compressing software and edit it using any text editors). Will consider to lowering the supported Pixelmon version range in the next Detector version, but I can't guarantee its stability in those lower versions. As a result, I highly recommend you to update your Pixelmon mod to recent one like 9.2.8. It's more stable than lower versions.

**Comment by Lileep** [comment]
Supported in the latest version. Have a try! :)
