### ISSUE TITLE
Unable to filter ivs

### ISSUE THREAD

**Issue by jiahuli** [Lileep/PixelmonDetector#32]
In 1.16.5, the search condition cannot search for ivs. No matter if I fill in iv=29 or the more detailed ivatk=29, it cannot search. Instead, it directly specifies the corresponding pokemon, even if the ivs requirement is not met. Select AND mode

**Comment by Lileep** [comment]
Hi there, ty for ur reply!
Have u set the `allowPokemonKeyInfo` in config to `true` before using? See [this wiki page](https://github.com/Lileep/PixelmonDetector/wiki/Configs#allowpokemonkeyinfo-boolean) to get more info about it. Feel free to reply again if u have any doubts. :)

**Comment by Lileep** [comment]
So it's been 2 weeks since ur question came up, have u solved this?

**Comment by Lukasfer** [comment]
hi lilpeep i'm not the author of the request but i've changed the 2 settings on true ( the one where you right click and the other ) but i can't see the difference nothing change . Could you please tell me how it works ?

**Comment by Lukasfer** [comment]
moreover is there any other feeturings that you think you'll add , like make more damages to pokemons or other things like affecting pokemons like mobs . ( To add some fun....)

**Comment by Lukasfer** [comment]
look at this video if you want https://www.youtube.com/watch?v=1itFOGlV4iY

**Comment by Lileep** [comment]
> moreover is there any other feeturings that you think you'll add , like make more damages to pokemons or other things like affecting pokemons like mobs . ( To add some fun....)

As for this, I'm sorry but I don't quite get what u're trying to introduce. Do you mean that you want deal damage to pokemons through player attacks? And make pokemon entities behave like vanilla mobs? If so, I don't think they should appear in Pixelmon Detector, because the Detector mod is designed for tracking pokemons conveniently. If you'd like to consider introducing these features you mentioned, I think it would be better to make another mod.

**Comment by Lukasfer** [comment]
perfect , thank you for the reply .

**Comment by Lileep** [comment]
> perfect , thank you for the reply .

Np, have a good time :D

**Comment by Lileep** [comment]
So it's been a month, has the issue been solved? I'm going to close this issue. If u have other questions, u can open a new issue to discuss :)
