### ISSUE TITLE
Can you add an option to filter poke_chest/ultra_chest/master_chest/beast_chest?

### ISSUE THREAD

**Issue by jiahuli** [Lileep/PixelmonDetector#33]
Can you add an option to filter poke_chest/ultra_chest/master_chest/beast_chest?

**Comment by Lileep** [comment]
Hi there, ty for ur reply!
There does exist an entry called `pokeLootFilter` in config file, u can remove any kind of PokeLoot from the entry if u don't want to track them. Feel free to reply if there're any doubts :)

**Comment by Emmet1119** [comment]
> Hi there, ty for ur reply! There does exist an entry called `pokeLootFilter` in config file, u can remove any kind of PokeLoot from the entry if u don't want to track them. Feel free to reply if there're any doubts :)

Doesn't exist as all I can see is the main JEI configuration file

**Comment by Lileep** [comment]
> > Hi there, ty for ur reply! There does exist an entry called `pokeLootFilter` in config file, u can remove any kind of PokeLoot from the entry if u don't want to track them. Feel free to reply if there're any doubts :)
> 
> Doesn't exist as all I can see is the main JEI configuration file

This mod can only edit ur client config. U can't edit the server's config via this mod. But u can find the `pixelmon-detector.toml` config file in ur `.minecraft/config` folder (client) or `config` folder (server), then open it with any kind of text editor software and edit it manually. Or just create a single player world and edit it using configure mod, u can't edit the server one from client after all.

**Comment by Lileep** [comment]
So it's been a month, has the issue been solved? I'm going to close this issue. If u have other questions, u can open a new issue to discuss :)
