### ISSUE TITLE
Is there a version that it doesn't put lines on every single pokeloot near you?

### ISSUE THREAD

**Issue by Emmet1119** [Lileep/PixelmonDetector#34]
So I play in a server which you can't access the pixelmon config menu so I'm stuck with these Yellow lines on my screen unless I turn off the radar. This is a question not a true issue

UPDATE: I forgot to mention this is 1.16.5

**Comment by Emmet1119** [comment]
> Hi there, ty for ur reply!
> 
> There're 2 configs named `drawLoots` and `pokeLootFilter` which allows u to control the tracking of PokeLoots:
> 
> * `drawLoots` determines if lines/markers/infos should be drawn for Poke Loots. There're 3 boolean elements in this config entry, represent whether lines/markers/infos should be drawn.  Setting all of them to `false` equals closing PokeLoot tracking.
> * `pokeLootFilter` means that only PokeLoot types listed in there will be tracked. U can remove Loot types that u don't wanna track, such as the lowest level PokeBall Loots.
> 
> The instructions can also be found in the comments of the Pixelmon Detector config file. See [this wiki page](https://github.com/Lileep/PixelmonDetector/wiki/Configs) to get more info.
> 
> However, if the server u're playing has also installed Detector, the client's config will follow the server one, which means that the decision-making power of the config is in the hands of the server owner rather than u.
> 
> Feel free to reply if there're any doubts! :)

How do you access the config? because from what I see I can't open it at all

**Comment by Lileep** [comment]
> > Hi there, ty for ur reply!
> > There're 2 configs named `drawLoots` and `pokeLootFilter` which allows u to control the tracking of PokeLoots:
> > 
> > * `drawLoots` determines if lines/markers/infos should be drawn for Poke Loots. There're 3 boolean elements in this config entry, represent whether lines/markers/infos should be drawn.  Setting all of them to `false` equals closing PokeLoot tracking.
> > * `pokeLootFilter` means that only PokeLoot types listed in there will be tracked. U can remove Loot types that u don't wanna track, such as the lowest level PokeBall Loots.
> > 
> > The instructions can also be found in the comments of the Pixelmon Detector config file. See [this wiki page](https://github.com/Lileep/PixelmonDetector/wiki/Configs) to get more info.
> > However, if the server u're playing has also installed Detector, the client's config will follow the server one, which means that the decision-making power of the config is in the hands of the server owner rather than u.
> > Feel free to reply if there're any doubts! :)
> 
> yeah I have the configure mod installed and it's showing nothing just the main Jei config file ![2024-08-12_04 32 33](https://private-user-images.githubusercontent.com/19894390/356997272-0416fe40-7643-4dc8-b007-dda6d39823b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzM1NTUsIm5iZiI6MTcyMzQ3MzI1NSwicGF0aCI6Ii8xOTg5NDM5MC8zNTY5OTcyNzItMDQxNmZlNDAtNzY0My00ZGM4LWIwMDctZGRhNmQzOTgyM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE0MzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDk0ODhhMjFkMTRlMjQyMmU4ZDAyYTllYTU5NThiOTgzMDU0MjI0MjNmNjBjY2JhN2JhYmYxNDg2NjRjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHTA4GaCxXA5iPxfljcxRVWJzYbokDrEZKRDtpoXkP0)

This mod can only edit ur client config. U can't edit the server's config via this mod. But u can find the `pixelmon-detector.toml` config file in ur `.minecraft/config` folder (client) or `config` folder (server), then open it with any kind of text editor software and edit it manually. Or just create a single player world and edit it using configure mod, u can't edit the server one from client after all.

**Comment by Lileep** [comment]
And the content displayed by ur configure mod doesn't look quite normal. Why does it show Just Enough Item on the title? It should show all config files of Forge itself even if u don't install Pixelmon or Pixelmon Detector. I still suggest u learn about the minecraft forge config file and how to directly edit it first, and don't be too obsessed with the configure mod.

**Comment by Lileep** [comment]
Here is what a standard 1.16.5 config file should look like:
![image](https://github.com/user-attachments/assets/bb0fcb6c-996e-4657-8da3-de9a5bedd1cb)

**Comment by Emmet1119** [comment]
tbh I just installed the Configured mod as the server did not have the radar or Configured installed and the image Was on a single player world

**Comment by Lileep** [comment]
> tbh I just installed the Configured mod as the server did not have the radar or Configured installed and the image Was on a single player world

Kinda weird. Then u can just try to edit the config manually follow the instructions I mentioned

**Comment by Emmet1119** [comment]
> Owner

I'm normally Not into Coding but I'll try

**Comment by Emmet1119** [comment]
Is it the first true the second one or the 3rd one because I can't tell at all

**Comment by Lileep** [comment]
> > Owner
> 
> I'm normally Not into Coding but I'll try

Umm, set configs via text editor actually has nothing to do with coding. Just edit it like how u edit a `.txt` file

**Comment by Emmet1119** [comment]
> > > Owner
> > 
> > 
> > I'm normally Not into Coding but I'll try
> 
> Umm, set configs via text editor actually has nothing to do with coding. Just edit it like how u edit a `.txt` file

I actually just found out which one of the 3 trues that I had to set false and it's the 1st one. here's my question why is it split into 3?

**Comment by Lileep** [comment]
> > > > Owner
> > > 
> > > 
> > > I'm normally Not into Coding but I'll try
> > 
> > 
> > Umm, set configs via text editor actually has nothing to do with coding. Just edit it like how u edit a `.txt` file
> 
> I actually just found out which one of the 3 trues that I had to set false and it's the 1st one. here's my question why is it split into 3?

I already told u at the beginning:

- `drawLoots` determines if lines/markers/infos should be drawn for Poke Loots. There're 3 boolean elements in this config entry, represent whether lines/markers/infos should be drawn. Setting all of them to false equals closing PokeLoot tracking.

**Comment by Lileep** [comment]
> Is it the first true the second one or the 3rd one because I can't tell at all

They separately present line, beam and info

**Comment by Lileep** [comment]
Btw, how did u play mods like twilight forest, botania, Create, or Immersive Craft if u don't know much about how to edit configs?

**Comment by Lileep** [comment]
I tried 1.16.5 Configured mod.  It performs well. Just:

1. Set a button u like and press it to open the screen. In my case I set it to `J`:

![QQ_1723531211910](https://github.com/user-attachments/assets/1ad02b27-11fa-4c4f-bd2a-165f10620719)

![QQ_1723531237704](https://github.com/user-attachments/assets/7f781a3f-abd2-4bcf-8b28-0b2394b9f987)

2. Select Pixelmon Detector and click the config button, then click the Modify button. Don't select JEI below

![QQ_1723531281804](https://github.com/user-attachments/assets/7b94da99-8e4c-4ef8-a62c-a8dc841172b3)

![QQ_1723531316415](https://github.com/user-attachments/assets/a659b41a-eaac-4e09-ab9b-68225fe69147)

![QQ_1723531338686](https://github.com/user-attachments/assets/972d91f2-10d4-4208-8fc4-7c3516f9b98c)

3. Just change whatever u want inside it:

![QQ_1723531364353](https://github.com/user-attachments/assets/f61f0b84-5129-4597-b198-5a02b059048e)

![QQ_1723531376925](https://github.com/user-attachments/assets/4a8f0e8e-150b-4764-901d-037376fc590b)

Have a try! :)

**Comment by Lileep** [comment]
So it's been a month, has the issue been solved? I'm going to close this issue. If u have other questions, u can open a new issue to discuss :)
