### ISSUE TITLE
Can it be updated to detect phantom beasts?

### ISSUE THREAD

**Issue by yingmeng66** [Lileep/PixelmonDetector#35]

**Comment by Lileep** [comment]
Hi, ty for ur reply!
I'm not familiar with phantom beasts, do u mean Mythical Legendary Pokemons like Mew and Deoxys? If so, the Detector does track them by default. Feel free to reply if u can provide more info :)

**Comment by Lileep** [comment]
Hi! So it's been 2 weeks, has this issue been resolved?

**Comment by Lileep** [comment]
I'll close this first. Feel free to ask again if u have any questions!
