### ISSUE TITLE
Filters set to "Or mode"

### ISSUE THREAD

**Issue by Magicperson1** [Lileep/PixelmonDetector#4]
Currently, when you set a filter (i.e. Hoot-Hoot and pygmy size) it shows all pokemon that mean ANY of those conditions.
I assume the attended behavior is they have to meet all of those conditions.

**Comment by Lileep** [comment]
Ok, so my idea is to add a button to toggle between "Or mode" and "And mode", I'll add this function in the next version. Ty for ur advice!

**Comment by Lileep** [comment]
Added in 1.1
