### ISSUE TITLE
Allowing for multiple form and growth selections

### ISSUE THREAD

**Issue by Magicperson1** [Lileep/PixelmonDetector#5]
It would be nice if you could filter for multiple form and growth options. Like I could filter for both pygmy and huge pokemon.

**Comment by Lileep** [comment]
Currently I don't have good ideas about applying multiple options. Maybe I can make some checkboxs for all filters.

Moreover, if u have ideas about implementing this function, then temporarily I can send u the code first and u can edit for this new feature. For issues about publishing this mod, view my reply in that issue, ty.

**Comment by Lileep** [comment]
> I would love to take a shot at it, feel free to send me the code

Glad that u're willing to help :) I'm not familiar with sending files in github, so I'll upload it to dropbox:

https://www.dropbox.com/s/3mszaha2fqhjmpq/PixelmonDetector.zip?dl=0

If it's not convenient for u, u can tell me ur email here and I'll send u one via email. Thx!

**Comment by Lileep** [comment]
Fixed in 1.2
