### ISSUE TITLE
Adding Gender detection

### ISSUE THREAD

**Issue by DarkVillager** [Lileep/PixelmonDetector#7]
Most servers also require gender for a hunt/challenge so adding this would be nice.

**Comment by Lileep** [comment]
Thx for ur reply!
This feature will be taken into account with the [multiple condition selections](https://github.com/Lileep/PixelmonDetector/issues/5). The filters might be changed to parameters in the next version, so u may write those filters in the search bar freely in future :)

**Comment by Lileep** [comment]
Fixed in 1.2
